[[constraint]]
  name = "github.com/bitrise-io/go-utils"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-io/goinp"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-tools/go-xamarin"
  branch = "master"

[[constraint]]
  name = "github.com/bitrise-tools/go-xcode"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  branch = "UITest"
  name = "github.com/bitrise-tools/xcode-project"
